[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
launchpad = "CqcCvZmiLwhgKJvhVzttVct2aHRW4n1dJFNiSpoJQHuq"

[registry]
url = "https://api.devnet.solana.com"

[provider]
cluster = "devnet"
endpoint = "https://api.devnet.solana.com"
websocket = "wss://api.devnet.solana.com"
disable_udp = true
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[build]
max-buffer-size = 400000